export enum Industry {
  SERVICIOS_FINANCIEROS = "SERVICIOS_FINANCIEROS",
  RETAIL = "RETAIL",
  ECOMMERCE = "ECOMMERCE",
  SALUD = "SALUD",
  EDUCACION = "EDUCACION",
  TECNOLOGIA = "TECNOLOGIA",
  LOGISTICA = "LOGISTICA",
  TURISMO = "TURISMO",
  HOSPITALIDAD = "HOSPITALIDAD",
  CONSULTORIA = "CONSULTORIA",
  LEGAL = "LEGAL",
  INMOBILIARIA = "INMOBILIARIA",
  ALIMENTOS = "ALIMENTOS",
  MODA = "MODA",
  EVENTOS = "EVENTOS",
  MARKETING = "MARKETING",
  ARQUITECTURA = "ARQUITECTURA",
  CONSTRUCCION = "CONSTRUCCION",
  ENERGIA = "ENERGIA",
  AGRICULTURA = "AGRICULTURA",
  ONG = "ONG",
  OTRO = "OTRO",
}

export enum BusinessModel {
  B2B = "B2B",
  B2C = "B2C",
  B2B2C = "B2B2C",
  MARKETPLACE = "MARKETPLACE",
}

export enum JtbdPrimary {
  AUTOMATIZAR_ATENCION = "AUTOMATIZAR_ATENCION",
  REDUCIR_TIEMPOS = "REDUCIR_TIEMPOS",
  ESCALAR_OPERACIONES = "ESCALAR_OPERACIONES",
  MEJORAR_EXPERIENCIA = "MEJORAR_EXPERIENCIA",
  LIBERAR_EQUIPO = "LIBERAR_EQUIPO",
  MULTIIDIOMA = "MULTIIDIOMA",
  DISPONIBILIDAD_24_7 = "DISPONIBILIDAD_24_7",
}

export enum PainPoints {
  VOLUMEN_ALTO = "VOLUMEN_ALTO",
  RESPUESTAS_LENTAS = "RESPUESTAS_LENTAS",
  FALTA_PERSONALIZACION = "FALTA_PERSONALIZACION",
  SOBRECARGA_EQUIPO = "SOBRECARGA_EQUIPO",
  CONSULTAS_REPETITIVAS = "CONSULTAS_REPETITIVAS",
  GESTION_MANUAL = "GESTION_MANUAL",
  PICOS_DEMANDA = "PICOS_DEMANDA",
  MULTICANAL = "MULTICANAL",
}

export enum LeadSource {
  LINKEDIN = "LINKEDIN",
  GOOGLE = "GOOGLE",
  CONFERENCIA = "CONFERENCIA",
  RECOMENDACION = "RECOMENDACION",
  WEBINAR = "WEBINAR",
  PODCAST = "PODCAST",
  FERIA = "FERIA",
  ARTICULO = "ARTICULO",
  NETWORKING = "NETWORKING",
  REDES_SOCIALES = "REDES_SOCIALES",
  DESCONOCIDO = "DESCONOCIDO",
}

export enum ProcessMaturity {
  MANUAL = "MANUAL",
  PARCIALMENTE_AUTOMATIZADO = "PARCIALMENTE_AUTOMATIZADO",
  AUTOMATIZADO = "AUTOMATIZADO",
}

export enum ToolingMaturity {
  SIN_HERRAMIENTAS = "SIN_HERRAMIENTAS",
  HERRAMIENTAS_BASICAS = "HERRAMIENTAS_BASICAS",
  CRM_INTEGRADO = "CRM_INTEGRADO",
}

export enum KnowledgeComplexity {
  SIMPLE = "SIMPLE",
  MODERADA = "MODERADA",
  COMPLEJA = "COMPLEJA",
}

export enum RiskLevel {
  BAJO = "BAJO",
  MEDIO = "MEDIO",
  ALTO = "ALTO",
}

export enum Integrations {
  CRM = "CRM",
  SISTEMA_CITAS = "SISTEMA_CITAS",
  ECOMMERCE = "ECOMMERCE",
  TICKETS = "TICKETS",
  RESERVAS = "RESERVAS",
  ERP = "ERP",
  WHATSAPP = "WHATSAPP",
  BASE_DATOS = "BASE_DATOS",
}

export enum Urgency {
  BAJA = "BAJA",
  MEDIA = "MEDIA",
  ALTA = "ALTA",
  INMEDIATA = "INMEDIATA",
}

export enum SuccessMetric {
  TIEMPO_RESPUESTA = "TIEMPO_RESPUESTA",
  VOLUMEN_PROCESADO = "VOLUMEN_PROCESADO",
  SATISFACCION_CLIENTE = "SATISFACCION_CLIENTE",
  REDUCCION_CARGA = "REDUCCION_CARGA",
  AHORRO_COSTOS = "AHORRO_COSTOS",
}

export enum Objections {
  COSTO = "COSTO",
  INTEGRACION = "INTEGRACION",
  CONFIDENCIALIDAD = "CONFIDENCIALIDAD",
  PERSONALIZACION = "PERSONALIZACION",
  COMPLEJIDAD = "COMPLEJIDAD",
}

export enum Sentiment {
  POSITIVO = "POSITIVO",
  NEUTRAL = "NEUTRAL",
  ESCEPTICO = "ESCEPTICO",
}

export enum VolumeUnit {
  DIARIO = "DIARIO",
  SEMANAL = "SEMANAL",
  MENSUAL = "MENSUAL",
}

export enum ExtractionStatus {
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  PENDING = "PENDING",
}

export enum SellerSortOrder {
  CLOSED = "CLOSED",
  CONVERSION_RATE = "CONVERSION_RATE",
}
